#!/usr/bin/env python3
"""
TATA SmartFlo -> inbound-dashboard-data.js sync.

Fetches call detail records from the SmartFlo API, transforms them into the
INBOUND_RECORDS shape the dashboard expects, and writes the data file
(and index.html's sibling copy is regenerated by the workflow).

Auth: the JWT token is passed as the raw `Authorization` header value
(no "Bearer " prefix), read from the TATA_TOKEN environment variable.

Run:  TATA_TOKEN=... DAYS_BACK=44 python scripts/sync.py
"""

import os
import sys
import json
import time
import datetime as dt
import urllib.request
import urllib.parse
import urllib.error

API_URL = "https://api-smartflo.tatateleservices.com/v1/call/records"
PAGE_LIMIT = 500          # records per page
CHUNK_DAYS = 28           # API caps each query window at 1 month; stay safely under
AFTER_HOURS_START = 20    # calls at hour >= 20 (8pm) count as after-hours
AFTER_HOURS_END = 9       # ...or before 9am
REQUEST_PAUSE = 0.3       # seconds between pages, be polite to the API
MAX_RETRIES = 4

# disposition_name -> (product, call_type) for lead classification.
# Anything not listed falls back to product "" and a best-effort ct.
DISPO_MAP = {
    "AM New":       ("AM", "New"),
    "AM Existing":  ("AM", "Existing"),
    "VO New":       ("VO", "New"),
    "VO Existing":  ("VO", "Existing"),
    "VO Queries":   ("VO", "Query"),
    "OD New":       ("OD", "New"),
    "OD Existing":  ("OD", "Existing"),
    "OD Queries":   ("OD", "Query"),
}

WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def token():
    t = os.environ.get("TATA_TOKEN", "").strip()
    if not t:
        sys.exit("ERROR: TATA_TOKEN environment variable is not set.")
    return t


def http_get(params, auth):
    """GET with retries. Returns parsed JSON dict."""
    url = API_URL + "?" + urllib.parse.urlencode(params)
    last_err = None
    for attempt in range(1, MAX_RETRIES + 1):
        req = urllib.request.Request(url, headers={
            "Authorization": auth,
            "accept": "application/json",
        })
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            last_err = f"HTTP {e.code}: {e.read().decode('utf-8', 'ignore')[:200]}"
            # 429 / 5xx are worth retrying
            if e.code in (429, 500, 502, 503, 504):
                time.sleep(2 * attempt)
                continue
            raise SystemExit(f"ERROR fetching {url}\n{last_err}")
        except (urllib.error.URLError, TimeoutError) as e:
            last_err = str(e)
            time.sleep(2 * attempt)
    raise SystemExit(f"ERROR: exhausted retries fetching page.\n{last_err}")


def fetch_all(auth, from_date, to_date):
    """Page through every record in the window."""
    all_rows = []
    page = 1
    while True:
        data = http_get({
            "from_date": from_date,
            "to_date": to_date,
            "page": page,
            "limit": PAGE_LIMIT,
        }, auth)
        results = data.get("results", []) or []
        all_rows.extend(results)
        count = int(data.get("count", 0) or 0)
        size = int(data.get("size", len(results)) or 0)
        got = (page - 1) * PAGE_LIMIT + size
        print(f"  page {page}: +{size} rows ({got}/{count})", flush=True)
        if size == 0 or got >= count:
            break
        page += 1
        time.sleep(REQUEST_PAUSE)
    return all_rows


def is_after_hours(hour):
    return hour >= AFTER_HOURS_START or hour < AFTER_HOURS_END


def classify(rec):
    """Transform one API record into the dashboard record, or None to drop it."""
    date = rec.get("date")
    ti = rec.get("time")
    if not date or not ti:
        return None

    try:
        hour = int(ti.split(":")[0])
    except (ValueError, IndexError):
        return None

    try:
        d = dt.date.fromisoformat(date)
        w = WEEKDAYS[d.weekday()]
    except ValueError:
        return None

    api_dir = (rec.get("direction") or "").lower()
    status = (rec.get("status") or "").lower()
    answered = status == "answered"
    dcd = rec.get("dialer_call_details") or {}
    dispo_name = (dcd.get("disposition_name") or "").strip()
    dispo_code = (dcd.get("disposition_code") or "").strip().upper()
    call_type = (dcd.get("call_type") or "").lower()
    missed_agents = rec.get("missed_agents") or []
    ah = 1 if is_after_hours(hour) else 0

    # ---- direction: inbound stays inbound; manual outbound = callback ----
    if api_dir == "inbound":
        dr = "inbound"
    elif api_dir == "outbound" and call_type == "manual":
        dr = "callback"
    else:
        # broadcast / dialer campaigns etc. — not part of the dashboard model
        return None

    # ---- miss type ----
    if answered:
        mt = "Answered"
    elif dr == "callback":
        mt = "Callback Missed"
    elif dispo_code == "QMISS" or "queue missed" in dispo_name.lower():
        mt = "Queue Missed - After Hours" if ah else "Queue Missed - Within Hours"
    elif missed_agents:
        mt = "Agent Missed"
    else:
        # inbound miss with no queue/agent signal: treat by hours
        mt = "Queue Missed - After Hours" if ah else "Queue Missed - Within Hours"

    # ---- product / call type from disposition ----
    pr, ct = "", ""
    if dispo_name in DISPO_MAP:
        pr, ct = DISPO_MAP[dispo_name]
    else:
        # keep the disposition label as ct when it isn't a product tag
        ct = dispo_name or ("Undisposed" if answered else "")

    # ---- numeric fields ----
    qt = int(dcd.get("call_wait_time") or 0)
    as_ = int(rec.get("answered_seconds") or 0)

    cn = rec.get("client_number") or ""
    # normalize to +91XXXXXXXXXX to match existing data
    digits = "".join(ch for ch in cn if ch.isdigit())
    if len(digits) == 10:
        cn = "+91" + digits
    elif digits.startswith("91") and len(digits) == 12:
        cn = "+" + digits
    elif cn and not cn.startswith("+"):
        cn = "+" + digits if digits else cn

    return {
        "d": date,
        "h": hour,
        "ti": ti,
        "w": w,
        "dr": dr,
        "st": "answered" if answered else "missed",
        "mt": mt,
        "ah": ah,
        "qt": qt,
        "as": as_,
        "pr": pr,
        "ct": ct,
        "cl": (rec.get("circle") or {}).get("circle") or "",
        "cn": cn,
        "ag": rec.get("agent_name") or "",
        "sc": rec.get("service") or "",
    }


def main():
    auth = token()
    days_back = int(os.environ.get("DAYS_BACK", "44"))
    today = dt.date.today()
    start = today - dt.timedelta(days=days_back - 1)

    # The API caps each date window at 1 month, so walk the range in chunks
    # and dedup by record id in case a boundary day overlaps.
    raw_by_id = {}
    chunk_start = start
    while chunk_start <= today:
        chunk_end = min(chunk_start + dt.timedelta(days=CHUNK_DAYS - 1), today)
        from_date = f"{chunk_start.isoformat()} 00:00:00"
        to_date = f"{chunk_end.isoformat()} 23:59:59"
        print(f"Chunk {from_date} -> {to_date} (limit {PAGE_LIMIT}/page)", flush=True)
        for rec in fetch_all(auth, from_date, to_date):
            rid = rec.get("id") or rec.get("call_id") or id(rec)
            raw_by_id[rid] = rec
        chunk_start = chunk_end + dt.timedelta(days=1)

    raw = list(raw_by_id.values())
    print(f"Fetched {len(raw)} unique raw records.", flush=True)

    records = [r for r in (classify(x) for x in raw) if r]
    # sort newest first within each day like the existing file (date asc, time desc within-day is fine either way)
    records.sort(key=lambda r: (r["d"], r["ti"]))
    print(f"Kept {len(records)} dashboard records.", flush=True)

    if not records:
        sys.exit("ERROR: no records after transform — aborting so we don't overwrite good data with empty.")

    dates = [r["d"] for r in records]
    generated_at = dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    out = []
    out.append("const INBOUND_RECORDS = " + json.dumps(records, separators=(",", ":"), ensure_ascii=False) + ";")
    out.append(f'const GENERATED_AT = "{generated_at}";')
    out.append(f'const DATE_FROM = "{min(dates)}";')
    out.append(f'const DATE_TO   = "{max(dates)}";')
    body = "\n".join(out) + "\n"

    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data_path = os.path.join(here, "inbound-dashboard-data.js")
    with open(data_path, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"Wrote {data_path} ({len(body):,} bytes, {len(records):,} records).", flush=True)


if __name__ == "__main__":
    main()
