#!/usr/bin/env python3
"""
TATA SmartFlo -> inbound-dashboard-data.js sync.

Fetches call detail records from the SmartFlo API, transforms them into the
INBOUND_RECORDS shape the dashboard expects, and writes the data file
(and index.html's sibling copy is regenerated by the workflow).

Auth: the JWT token is passed as the raw `Authorization` header value
(no "Bearer " prefix), read from the TATA_TOKEN environment variable.

Run:  TATA_TOKEN=... DAYS_BACK=44 python scripts/sync.py
"""

import os
import sys
import json
import time
import datetime as dt
import urllib.request
import urllib.parse
import urllib.error

API_URL = "https://api-smartflo.tatateleservices.com/v1/call/records"
PAGE_LIMIT = 500          # records per page
CHUNK_DAYS = 28           # API caps each query window at 1 month; stay safely under
REQUEST_PAUSE = 0.3       # seconds between pages, be polite to the API
MAX_RETRIES = 4

# disposition_name -> (product, call_type). Per dashboard-rules.pdf Rule 6.2.
# Products map to AM/VO/OD; non-product tags keep pr="" with a normalized ct.
DISPO_MAP = {
    "AM New":                 ("AM", "New"),
    "AM Existing":            ("AM", "Existing"),
    "VO New":                 ("VO", "New"),
    "VO Existing":            ("VO", "Existing"),
    "VO Queries":             ("VO", "Query"),
    "OD New":                 ("OD", "New"),
    "OD Existing":            ("OD", "Existing"),
    "OD Queries":             ("OD", "Query"),
    # non-product dispositions (pr stays blank)
    "Others":                 ("", "Other"),
    "Voice Mail":             ("", "Voice Mail"),
    "Did Not Respond":        ("", "Did Not Respond"),
    "Invalid Num":            ("", "Invalid"),
    "Undisposed":             ("", "Undisposed"),
    "Queue Missed":           ("", ""),
    "Missed By Agent":        ("", "Missed By Agent"),
    "Receiver is Busy":       ("", "Busy"),
    "System Failure":         ("", "System Failure"),
    "Call Rejected":          ("", "Call Rejected"),
    "Not Reachable":          ("", "Not Reachable"),
    "No Answer":              ("", "No Answer"),
    "Network / Channel Issue": ("", "Network/Channel Issue"),
}

WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def token():
    t = os.environ.get("TATA_TOKEN", "").strip()
    if not t:
        sys.exit("ERROR: TATA_TOKEN environment variable is not set.")
    return t


def http_get(params, auth):
    """GET with retries. Returns parsed JSON dict."""
    url = API_URL + "?" + urllib.parse.urlencode(params)
    last_err = None
    for attempt in range(1, MAX_RETRIES + 1):
        req = urllib.request.Request(url, headers={
            "Authorization": auth,
            "accept": "application/json",
        })
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            last_err = f"HTTP {e.code}: {e.read().decode('utf-8', 'ignore')[:200]}"
            # 429 / 5xx are worth retrying
            if e.code in (429, 500, 502, 503, 504):
                time.sleep(2 * attempt)
                continue
            raise SystemExit(f"ERROR fetching {url}\n{last_err}")
        except (urllib.error.URLError, TimeoutError) as e:
            last_err = str(e)
            time.sleep(2 * attempt)
    raise SystemExit(f"ERROR: exhausted retries fetching page.\n{last_err}")


def _paginate(auth, from_date, to_date, direction):
    """Page through one direction of the window."""
    all_rows = []
    page = 1
    while True:
        data = http_get({
            "from_date": from_date,
            "to_date": to_date,
            "direction": direction,
            "page": page,
            "limit": PAGE_LIMIT,
        }, auth)
        results = data.get("results", []) or []
        all_rows.extend(results)
        count = int(data.get("count", 0) or 0)
        size = int(data.get("size", len(results)) or 0)
        got = (page - 1) * PAGE_LIMIT + size
        print(f"  [{direction}] page {page}: +{size} rows ({got}/{count})", flush=True)
        if size == 0 or got >= count:
            break
        page += 1
        time.sleep(REQUEST_PAUSE)
    return all_rows


def fetch_all(auth, from_date, to_date):
    """Mirror tata_sync.py exactly — three sources, deduped later by call_id:
      1. Inbound-type records from the outbound feed (call_type == 'inbound')
      2. Callbacks from the outbound feed (call_type != 'inbound')
      3. Direct/after-hours inbound calls from the inbound feed
    """
    outbound = _paginate(auth, from_date, to_date, "outbound")
    inbound_calls = [r for r in outbound
                     if (r.get("dialer_call_details") or {}).get("call_type", "").lower() == "inbound"]
    callbacks = [r for r in outbound
                 if (r.get("dialer_call_details") or {}).get("call_type", "").lower() != "inbound"]
    raw_inbound = _paginate(auth, from_date, to_date, "inbound")
    return inbound_calls + callbacks + raw_inbound


def is_after_hours(hour, service, description):
    """Rule 1.4: after-hours if service/description mentions 'After office',
    OR the call hour is outside 9:00-19:59 (before 9am or 8pm+)."""
    text = (service + " " + description).lower()
    if "after office" in text:
        return True
    return hour < 9 or hour >= 20


def classify(rec):
    """Transform one API record into the dashboard record, or None to drop it.
    Follows dashboard-rules.pdf v1.0."""
    date = rec.get("date")
    ti = rec.get("time")
    if not date or not ti:
        return None

    try:
        hour = int(ti.split(":")[0])
    except (ValueError, IndexError):
        return None

    try:
        d = dt.date.fromisoformat(date)
        w = WEEKDAYS[d.weekday()]
    except ValueError:
        return None

    status = (rec.get("status") or "").lower()
    answered = status == "answered"
    dcd = rec.get("dialer_call_details") or {}
    dispo_name = (dcd.get("disposition_name") or "").strip()
    call_type = (dcd.get("call_type") or "").lower()
    service = rec.get("service") or ""
    description = rec.get("description") or ""
    ah = is_after_hours(hour, service, description)

    # ---- Direction (tata_sync.derive_call_direction) ----
    #   no dialer context      -> inbound (direct CloudPhone call)
    #   dcd.call_type=="inbound" -> inbound
    #   else                    -> callback
    if not dcd:
        dr = "inbound"
    elif call_type == "inbound":
        dr = "inbound"
    else:
        dr = "callback"

    # ---- Miss type (tata_sync.derive_missed_type) ----
    if answered:
        mt = "Answered"
    elif dr == "callback":
        mt = "Callback Missed"
    elif ah:
        mt = "Queue Missed - After Hours"
    elif dispo_name == "Missed By Agent":
        mt = "Agent Missed"
    else:
        mt = "Queue Missed - Within Hours"

    # ---- Product / call type from disposition (Rule 6.2) ----
    pr, ct = "", ""
    if dispo_name in DISPO_MAP:
        pr, ct = DISPO_MAP[dispo_name]
    else:
        # keep the disposition label as ct when it isn't a product tag
        ct = dispo_name or ("Undisposed" if answered else "")

    # ---- numeric fields ----
    qt = int(dcd.get("call_wait_time") or 0)
    as_ = int(rec.get("answered_seconds") or 0)

    cn = rec.get("client_number") or ""
    # normalize to +91XXXXXXXXXX to match existing data
    digits = "".join(ch for ch in cn if ch.isdigit())
    if len(digits) == 10:
        cn = "+91" + digits
    elif digits.startswith("91") and len(digits) == 12:
        cn = "+" + digits
    elif cn and not cn.startswith("+"):
        cn = "+" + digits if digits else cn

    return {
        "d": date,
        "h": hour,
        "ti": ti,
        "w": w,
        "dr": dr,
        "st": "answered" if answered else "missed",
        "mt": mt,
        "ah": 1 if ah else 0,
        "qt": qt,
        "as": as_,
        "pr": pr,
        "ct": ct,
        "cl": (rec.get("circle") or {}).get("circle") or "",
        "cn": cn,
        "ag": rec.get("agent_name") or "",
        "sc": rec.get("service") or "",
    }


def main():
    auth = token()
    days_back = int(os.environ.get("DAYS_BACK", "44"))
    today = dt.date.today()
    start = today - dt.timedelta(days=days_back - 1)

    # The API caps each date window at 1 month, so walk the range in chunks
    # and dedup by record id in case a boundary day overlaps.
    raw_by_id = {}
    chunk_start = start
    while chunk_start <= today:
        chunk_end = min(chunk_start + dt.timedelta(days=CHUNK_DAYS - 1), today)
        from_date = f"{chunk_start.isoformat()} 00:00:00"
        to_date = f"{chunk_end.isoformat()} 23:59:59"
        print(f"Chunk {from_date} -> {to_date} (limit {PAGE_LIMIT}/page)", flush=True)
        for rec in fetch_all(auth, from_date, to_date):
            # Dedup by call_id exactly like tata_sync.py (the outbound + inbound
            # feeds overlap; call_id is the stable key).
            rid = rec.get("call_id") or rec.get("uuid") or id(rec)
            raw_by_id[rid] = rec
        chunk_start = chunk_end + dt.timedelta(days=1)

    raw = list(raw_by_id.values())
    print(f"Fetched {len(raw)} unique raw records.", flush=True)

    records = [r for r in (classify(x) for x in raw) if r]
    # sort newest first within each day like the existing file (date asc, time desc within-day is fine either way)
    records.sort(key=lambda r: (r["d"], r["ti"]))
    print(f"Kept {len(records)} dashboard records.", flush=True)

    if not records:
        sys.exit("ERROR: no records after transform — aborting so we don't overwrite good data with empty.")

    dates = [r["d"] for r in records]
    generated_at = dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    out = []
    out.append("const INBOUND_RECORDS = " + json.dumps(records, separators=(",", ":"), ensure_ascii=False) + ";")
    out.append(f'const GENERATED_AT = "{generated_at}";')
    out.append(f'const DATE_FROM = "{min(dates)}";')
    out.append(f'const DATE_TO   = "{max(dates)}";')
    body = "\n".join(out) + "\n"

    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data_path = os.path.join(here, "inbound-dashboard-data.js")
    with open(data_path, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"Wrote {data_path} ({len(body):,} bytes, {len(records):,} records).", flush=True)


if __name__ == "__main__":
    main()
